/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 3e05d10aa3855312c77f4679ed7c0e5b)
interface __BaseEnv_Env {
	DIRECTORY_DB: D1Database;
	ASSETS: Fetcher;
	ENVIRONMENT: "production";
	BOOTSTRAP_CODE_HASH: "40838a82adcdb4c8fb91354cf222adb93892b94739975fac956ff9029dbf4c5e";
	TEAM_ROOMS: DurableObjectNamespace<import("./worker/index").TeamRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "TeamRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "BOOTSTRAP_CODE_HASH">> {}
}
