/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: ed22af8f40825a78f5e800b2ef349214)
interface __BaseEnv_Env {
	DIRECTORY_DB: D1Database;
	ASSETS: Fetcher;
	ENVIRONMENT: "production";
	BOOTSTRAP_CODE_HASH: "40838a82adcdb4c8fb91354cf222adb93892b94739975fac956ff9029dbf4c5e";
	APP_BASE_URL: "https://manager.soccergrowthhub.com/";
	INVITE_FROM_ADDRESS: "team@soccergrowthhub.com";
	TEAM_ROOMS: DurableObjectNamespace<import("./worker/index").TeamRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "TeamRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "BOOTSTRAP_CODE_HASH" | "APP_BASE_URL" | "INVITE_FROM_ADDRESS">> {}
}
